
import React from 'react';
import { Shield } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const HomePage = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center text-white px-4">
            <div className="max-w-3xl text-center space-y-8 animate-fade-in-up">
                <div className="flex justify-center mb-6">
                    <div className="w-24 h-24 bg-indigo-600 rounded-2xl flex items-center justify-center shadow-lg shadow-indigo-500/50">
                        <Shield size={64} className="text-white" />
                    </div>
                </div>

                <h1 className="text-6xl font-black tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-cyan-400">
                    CogniPhish
                </h1>

                <h2 className="text-2xl text-gray-400 font-light">
                    AI-Powered Dunning-Kruger Phishing Simulator
                </h2>

                <p className="text-lg text-gray-300 leading-relaxed max-w-2xl mx-auto">
                    Most phishing training fails because it doesn't account for <strong>human psychology</strong>.
                    This simulator uses AI to generate realistic attacks and measures not just your accuracy,
                    but your <strong>overconfidence</strong>.
                </p>

                <div className="bg-slate-800 p-6 rounded-xl border border-slate-700 text-left space-y-4 shadow-xl">
                    <div className="flex items-start space-x-4">
                        <span className="text-2xl">🧠</span>
                        <div>
                            <h3 className="font-bold text-white">The Psychology of Risk</h3>
                            <p className="text-gray-400 text-sm">We track the "Dunning-Kruger" effect—where high confidence on wrong answers leads to the highest risk scores.</p>
                        </div>
                    </div>
                    <div className="flex items-start space-x-4">
                        <span className="text-2xl">🤖</span>
                        <div>
                            <h3 className="font-bold text-white">AI-Forged Attacks</h3>
                            <p className="text-gray-400 text-sm">Every email is uniquely generated by an AI agent (The Forge) to adapt to your blind spots.</p>
                        </div>
                    </div>
                </div>

                <button
                    onClick={() => navigate('/simulation')}
                    className="group relative px-8 py-4 bg-indigo-600 rounded-full text-xl font-bold hover:bg-indigo-500 transition-all shadow-[0_0_20px_rgba(79,70,229,0.5)] hover:shadow-[0_0_40px_rgba(79,70,229,0.7)]"
                >
                    Start Simulation
                    <span className="absolute right-4 top-1/2 transform -translate-y-1/2 opacity-0 group-hover:opacity-100 group-hover:translate-x-2 transition-all">→</span>
                </button>
            </div>
        </div>
    );
};

export default HomePage;
